// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFOmvfuo88VdjQrsFQ3XEt4f4dJnGiGc',
    appId: '1:100781697007:web:1f9d76d637b4a14b9ff81a',
    messagingSenderId: '100781697007',
    projectId: 'practice-app-apptech',
    authDomain: 'practice-app-apptech.firebaseapp.com',
    storageBucket: 'practice-app-apptech.appspot.com',
    databaseURL: 'https://practice-app-apptech-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJevryXAYmlmCSCYfj_awhy8QhAZV1w2Y',
    appId: '1:100781697007:android:6b2fa2ef0651d2e69ff81a',
    messagingSenderId: '100781697007',
    projectId: 'practice-app-apptech',
    storageBucket: 'practice-app-apptech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvBdwYcGq7GyK-ZF_Y8kFyZ1hUmZOtoE',
    appId: '1:100781697007:ios:a84eae651020b89e9ff81a',
    messagingSenderId: '100781697007',
    projectId: 'practice-app-apptech',
    storageBucket: 'practice-app-apptech.appspot.com',
    iosBundleId: 'com.example.flutterPracticeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvBdwYcGq7GyK-ZF_Y8kFyZ1hUmZOtoE',
    appId: '1:100781697007:ios:a84eae651020b89e9ff81a',
    messagingSenderId: '100781697007',
    projectId: 'practice-app-apptech',
    storageBucket: 'practice-app-apptech.appspot.com',
    iosBundleId: 'com.example.flutterPracticeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChFOmvfuo88VdjQrsFQ3XEt4f4dJnGiGc',
    appId: '1:100781697007:web:e07f63213087e9fb9ff81a',
    messagingSenderId: '100781697007',
    projectId: 'practice-app-apptech',
    authDomain: 'practice-app-apptech.firebaseapp.com',
    storageBucket: 'practice-app-apptech.appspot.com',
  );
}
